name: Cleanup Artifacts
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete old artifacts
      uses: actions/delete-artifact@v1
      with:
        age: '7'  # Delete artifacts older than 7 days
