# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy RSS Feed Site

on:
#  push:
#    paths:
#      - 'C4PHub.RssApi/**'
#      - 'C4PHub.StorageAccount/*'
#      - 'C4PHub.Core/**'
#      - 'C4PHub.Sessionize/**'
#    branches:
#     - main
 workflow_dispatch:

env:
    WEBAPP_ROOT: ${{ github.workspace }}/C4PHub.RssApi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
          include-prerelease: false
          
      - name: retrieve datetime from action
        id: getDate
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "1.YYYY.MMDD"

      - name: Set version in all AssemblyInfo.cs files
        id: set-assembly-version
        uses: secondbounce/assemblyinfo-update@v2
        with:
          version: ${{ steps.getDate.outputs.time }}
          directory: '${{ env.WEBAPP_ROOT }}'
          recursive: false
      
      - name: Build with dotnet
        run: dotnet build ${{ env.WEBAPP_ROOT }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.WEBAPP_ROOT }} -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'c4phubfeed'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_RSSAPI_PUBLISHPROFILE }}
